### ISSUE TITLE
how can compile

### ISSUE THREAD

**Issue by lastblade** [sjitech/ApkRename#3]
there is no releases.
how can i compile this please ?

**Comment by jjqq2013** [comment]
No need to compile. 
lib/AndroidManifestBinaryXml_ChangePackageName/bin already contains precompiled binary files(*.jar). You can just download all and use it. 
If your really want to change and compile lib/AndroidManifestBinaryXml_ChangePackageName project, please use eclipse to import project in the dir then build it(already configured to output to bin dir)

**Comment by lastblade** [comment]
Do i need some specific java version ?
i click on it and nothing happens.

**Comment by jjqq2013** [comment]
Use need open Eclipse, -> File -> Import -> Java Project -> Choose directory where you downloaded.
Then build
